export { default as HomeScreen } from './Home'
export { default as ProfileScreen } from './Profile'
export { default as Login } from './Login'
export { default as Settings } from './Settings'
export { default as Splashscreen} from './Splashscreen'